// Generated by https://quicktype.io

export interface ApplyVaccineResponse {
    apply_vaccines: ApplyVaccine[];
    desde:          number;
    limite:         number;
    resp:           boolean;
    statusCode:     number;
    total:          number;
}

export interface ApplyVaccine {
    _id:              ID;
    dependent:        Dependent;
    dependent_id:     string;
    dosis:            Dosis;
    dosis_id:         string;
    image:            string;
    lote:             string;
    status:           boolean;
    vaccination_date: string;
}

export interface ID {
    $oid: string;
}

export interface Dependent {
    _id:             ID;
    age:             number;
    birth:           string;
    city:            string;
    email:           string;
    gender_id:       string;
    isChildren:      boolean;
    isUser:          boolean;
    lastname:        string;
    name:            string;
    phone:           string;
    relationship_id: string;
    state:           string;
    status:          boolean;
    user_id:         string;
}

export interface Dosis {
    _id:           ID;
    age_frequency: string;
    name:          string;
    status:        boolean;
    vaccine:       Vaccine;
    vacinne_id:    string;
}

export interface Vaccine {
    _id:              ID;
    application_age:  string;
    description:      string;
    disease_prevents: string;
    isChildren:       boolean;
    name:             string;
    status:           boolean;
}
