// Generated by https://quicktype.io

export interface Dependentss {
    dependents: Dependent[];
    desde:      number;
    limite:     number;
    total:      number;
}


export interface Dependent {
    _id?:             ID;
    age?:             number;
    birth?:           Date;
    email?:           string;
    gender_id?:       string;
    isChildren?:      boolean;
    isUser?:          boolean;
    lastname?:        string;
    name?:            string;
    phone?:           string;
    relationship_id?: string;
    status?:          boolean;
    user_id?:         string;
   
}

export interface ID {
    $oid: string;
}


export interface DesdeLimite {
    desde:      number;
    limite:     number;
}
 