// Generated by https://quicktype.io

export interface DosisResponse {
    desde:  number;
    dosiss: Dosiss[];
    limite: number;
    total:  number;
}

export interface Dosiss {
    _id:           ID;
    age_frequency: string;
    name:          string;
    status:        boolean;
    vacinne_id:    string;
}

export interface ID {
    $oid: string;
}
