// Generated by https://quicktype.io

export interface DosisResponse {
    _id:           ID;
    vacinne_id:    string;
    name:          string;
    age_frequency: string;
    status:        boolean;
}

export interface ID {
    $oid: string;
}
