export * from "./appInterfaces"
export * from "./register-interfaces"
export * from './appInterfaces'
export * from './vaccinesinterface'
export * from './login-interface'
export * from './dependent-interfaces'
export * from './handlerPage-interface'
export * from './perfil-figma-interfaces'
export * from './constantes'
export * from './apply-vaccines-interfaces'
export * from './dosis-vaccines-interfaces'
