// Generated by https://quicktype.io

export interface Register {
    name:      string;
    lastname:  string;
    password:  string;
    ci:        string;
    email:     string;
    state:     string;
    city:      string;
    birth:     string;
    gender_id: string;
    status:    string;
    token?:    string;
    resp?:     boolean;
}
