// Generated by https://quicktype.io

export interface RelationShipResponse {
    desde:         number;
    limite:        number;
    relationships: Relationship[];
    total:         number;
}

export interface Relationship {
    _id:    ID;
    name:   string;
    status: boolean;
}

export interface ID {
    $oid: string;
}
