// Generated by https://quicktype.io

export interface VaccineResponse {
    desde:    number;
    limite:   number;
    total:    number;
    vaccines: Vaccine[];
}

export interface Vaccine {
    _id?:              ID;
    application_age?:  string;
    description?:      string;
    disease_prevents?: string;
    isChildren?:       boolean;
    name?:             string;
    status?:           boolean;
}

export interface ID {
    $oid: string;
}
