// Generated by https://quicktype.io

//############################SendSms#######################################################
export interface SendSmsRequest {
    phone:      string;
}

export interface CheckcCodeRequest {
    phone?:      string | null | undefined;
    code?:      string | null | undefined;
}

export interface CheckcCodeResponse {
    statusCode?: number;
    resp?:       boolean;
    message?:    string;
    token?:      string;
}
 

export interface SendSmsResponse {
    statusCode?: number;
    resp?:      boolean;
    error?:     string;
    message?:    string;
}
//############################SendSms End###################################################

export interface LoginVaccineResponse {
    statusCode: number;
    token:      string;
    usuario:    Usuario;
    more:       More;
    resp?:       boolean;
}

export interface More {
    _id:       ID;
    name:      string;
    lastname:  string;
    email:     string;
    birth:     string;
    gender_id: string;
    status:    string;
    isUser:    boolean;
    user_id:   ID;
}

export interface ID {
    $oid: string;
}

export interface Usuario {
    _id:       ID;
    phone:     string;
    last_code: number;
    status:    string;
    token:     string;
    ci:        string;
    city:      string;
    password:  string;
    state:     string;
    img?:      string;
}
