 // Generated by https://quicktype.io

export interface VaccineWithDosisforDependentResponse {
    vacc_apply_vaccines: Array<VaccApplyVaccine | null>;
    statusCode:          number;
    resp:                boolean;
}

export interface VaccApplyVaccine {
    vaccine?: Vaccine;
    dosis?:   Dosi[];
}

export interface Dosi {
    _id:              ID;
    vacinne_id:       string;
    name:             string;
    age_frequency:    string;
    status:           boolean;
    isApplied:        boolean;
    lote:             null;
    image:            null;
    vaccination_date: null;
    dependentId:      string;
    dosisId:          string;
}

export interface ID {
    $oid: string;
}

export interface Vaccine {
    _id:              ID;
    name:             string;
    description:      string;
    disease_prevents: string;
    application_age:  string;
    isChildren:       boolean;
    status:           boolean;
    lote:             null;
    isApplied?:        boolean;

}
