// Generated by https://quicktype.io

export interface CalendarVaccineByDependentResponse {
    title: string;
    data: CalendarVaccineDependent[];
}

export interface CalendarVaccineDependent {
    datevaccine?:            string;
    name?:                   string;
    dosisMissingandAplied?:  string;
}


