// Generated by https://quicktype.io

export interface CalendarVaccineByDependentResponse {
    title: string;
    data: CalendarVaccineDependent[];
}

export interface CalendarVaccineDependent {
    datevaccine?:            string;
    nameLastnameDependent?:                   string;
    dosisMissingandAplied?:  string;

    titleVaccine ? : string;
    dosisApplied? : number;
    ofCountDosis ? : number;
    titleDosis?: string[];
}


