// Generated by https://quicktype.io

export interface VaccineEditCreateResponse {
    desde:    number;
    limite:   number;
    total:    number;
    vaccines: Vaccine[];
}

// Generated by https://quicktype.io

export interface VaccineByIDResponse {
    _id:              ID;
    name:             string;
    description:      string;
    disease_prevents: string;
    application_age:  string;
    isChildren:       boolean;
    status:           boolean;
    dosis_ids:        any[];
}

export interface ID {
    $oid: string;
}

 

export interface Vaccine {
    _id:              ID;
    application_age:  string;
    description:      string;
    disease_prevents: string;
    isChildren:       boolean;
    name:             string;
    status:           boolean;
}

export interface ID {
    $oid: string;
}


// Generated by https://quicktype.io

export interface VaccinePostResponse {
    id:               string;
    name:             string;
    description:      string;
    disease_prevents: string;
    application_age:  string;
    isChildren:       boolean;
    status:           boolean;
}

// Generated by https://quicktype.io

export interface VaccinePutResponse {
    _id:         ID;
    error:      boolean;
    resp:       boolean;
    TypeError:  string;
    statusCode: string;
    ValueError: string;
    message:    string;
}

