// Generated by https://quicktype.io

export interface DependentBDResponse {
    dependents: DependentBD[];
    desde:      number;
    limite:     number;
    total:      number;
}

export interface DependentBD {
    _id:        ID;
    age:        number;
    birth:      string;
    days_birth: number;
    email:      string;
    gender_id:  string;
    isChildren: boolean;
    isUser:     boolean;
    lastname:   string;
    name:       string;
    phone:      string;
    status:     boolean;
    token:      string;
    user_id:    ID;
}

export interface ID {
    $oid: string;
}
