// Generated by https://quicktype.io

export interface DependentIDResponseBD {
    result: DependentById;
}

export interface DependentById {
    _id?:        ID;
    name?:       string;
    lastname?:   string;
    email?:      string;
    birth?:       Date | null;
    gender_id?:  string;
    relationship_id?: string | null;
    status?:     boolean | string;
    token?:      string;
    phone?:      string;
    isUser?:     boolean;
    user_id?:    string;
    isChildren?: boolean;
    age?:        number;
    days_birth?: number;
    state? : string;
    city? : string;
}

export interface IDBD {
    $oid: string;
}


export interface DependentIDResponse {
    result: Result;
}

export interface Result {
    _id:        ID;
    name:       string;
    lastname:   string;
    email:      string;
    birth:      string;
    gender_id:  string;
    relationship_id?: string | null;
    status:     boolean;
    token:      string;
    phone:      string;
    isUser:     boolean;
    user_id:    ID;
    isChildren: boolean;
    age:        number;
    days_birth: number;
}

export interface ID {
    $oid: string;
}

// Generated by https://quicktype.io

export interface DependentUpdateCreateResponse {
    statusCode: number;
    resp:       boolean;
    message:    string;
    _id:       ID;
}

// Generated by https://quicktype.io

export interface DependentCreateResponse {
    statusCode:   number;
    resp:         boolean;
    age:          number;
    days_birth:   number;
    message:      string;
    dependentNew: DependentNew;
}

export interface DependentNew {
    $oid: string;
}
