 // Generated by https://quicktype.io


 export interface DosisByIdEntity {
    _id?:             ID;
    name?:            string;
    age_frequency?:   string;
    expires_in_days?: number;
    status?:          boolean;
    rowReporte?:      string;
    columReporte?:    string;
    vacinne_id?:         string;

    error?:      boolean;
    resp?:       boolean;
    TypeError?:  string;
    statusCode?: string;
    ValueError?: string;
    message?:    string;
}

export interface ID {
    $oid: string;
}

export interface Vaccine {
    _id:              ID;
    name:             string;
    description:      string;
    disease_prevents: string;
    application_age:  string;
    isChildren:       boolean;
    status:           boolean;
    dosis_ids:        any[];
}