// Generated by https://quicktype.io

export interface ParentescoEntity {
    desde:         number;
    limite:        number;
    relationships: Relationship[];
    total:         number;
}

export interface Relationship {
    _id:    ID;
    name:   string;
    statusCode?:string | number;
    status: boolean;
    resp?:boolean;
    message?:string;
}

export interface ID {
    $oid: string;
}

 