import { Vaccine } from "./VaccineDependent";

export interface VaccineEditCreateEntiy {
    desde:    number;
    limite:   number;
    total:    number;
    vaccines: Vaccine[];
}

// export interface Vaccine {
//     _id:              ID;
//     application_age:  string;
//     description:      string;
//     disease_prevents: string;
//     isChildren:       boolean;
//     name:             string;
//     isChecked?:          boolean;
//     status:           boolean;
// }

export interface ID {
    $oid: string;
}

export interface VaccinePostEntity {
    id:               string;
    name:             string;
    description:      string;
    disease_prevents: string;
    application_age:  string;
    isChildren:       boolean;
    status:           boolean;
}

export interface VaccinePutEntity {
    error:      boolean;
    resp:       boolean;
    TypeError:  string;
    statusCode: string;
    ValueError: string;
    message:    string;
}

export interface VaccinePutPostResponseEntity {
    _id:              ID;
    error:      boolean;
    resp:       boolean;
    TypeError:  string;
    statusCode: number;
    ValueError: string;
    message:    string;
}

export interface VaccineByIDEntity {
    _id:              ID;
    name:             string;
    description:      string;
    disease_prevents: string;
    application_age:  string;
    isChildren:       boolean;
    status:           boolean;
    dosis_ids:        DosisEntity[];
}
 

// Generated by https://quicktype.io

export interface DosisEntity {
//DATOS DE LA VACUNA
    vaccineID?:              ID;
    vaccineName?:             string;
    vaccineDescription?:      string;
    vaccineDisease_prevents?: string;
    vaccineApplication_age?:  string;
    vaccineIsChildren?:       boolean;
    vaccineStatus?:           boolean;
 //DATOS DE LA DOSIS
    _id:             ID;
    vacinne_id:      string;
    name:            string;
    age_frequency:   string;
    status:          boolean;
    columReporte:    string;
    rowReporte:      string;
    expires_in_days: number;


}

export interface ID {
    $oid: string;
}
