service: vaccine #na

provider:
 name: aws
 runtime: python3.11
 region: us-east-1
 memorySize: 128
 environment:
    STRIP_STAGE_PATH: yes
    MONGO_URI: 'mongodb+srv://simon:XhlUSILsriC0H3bO@micluster.mayzd.mongodb.net/mic_serv_users'
    TWILIO_ID: 'ACe7edfd31cf39b1e25f717ed5093a81fc'
    TWILIO_AUTH_TOKEN: '16b8ed08adc0a9530c74a9df53e2d47d'
    JWT_SECRET: 'ASDASDJAWJDAIEJEIADJWDADKWOAJ'
    TWILIO_PHONE: '+12179190616'

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
 wsgi:
   app: app.app
   packRequirements: false

functions:
 app:
   handler: wsgi_handler.handler
   events:
     - httpApi: '*'
