service: mic-serv-vaccine
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
