service: national-vaccine-control-app
useDotenv: true
frameworkVersion: "3"
CorsConfiguration:
  AllowOrigins:
    - "http://localhost:4200/"
  AllowHeaders:
    - x-apigateway-header
  AllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
  MaxAge: 600
  AllowCredentials: true
provider:
  name: aws
  runtime: python3.9
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
    MONGO_URI: mongodb+srv://simon:XhlUSILsriC0H3bO@micluster.mayzd.mongodb.net/health_{{stage}}
    TWILIO_ID: 'ACe7edfd31cf39b1e25f717ed5093a81fc'
    TWILIO_AUTH_TOKEN: '46d118856fadd22a1853c4ab6abb0e02'
    JWT_SECRET: 'ASDASDJAWJDAIEJEIADJWDADKWOAJ'
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
package:
  individually: true
  patterns:
    - "!*/**"
plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  pythonRequirements:
    usePipenv: false
    dockerizePip: true
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
      - qa
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  # TOKEN
  verify-token:
    handler: Token/handler.verifyToken
    package:
      patterns:
        - "Token/handler.py"
# PHONE
  send-sms:
    handler: Phone/sendSms/handler.sendSms
    package:
      patterns:
        - "Phone/sendSms/handler.py"
    events:
      - http:
          path: sendsms
          method: POST
          request:
            schemas:
              application/json: ${file(Phone/sendSms/phone-schema.json)}
  check-code:
    handler: Phone/checkCode/handler.checkCode
    package:
      patterns:
        - "Phone/checkCode/handler.py"
    events:
      - http:
          path: checkcode
          method: POST
          request:
            schemas:
              application/json: ${file(Phone/checkCode/code-schema.json)}
    # USERS
  add-users:
    handler: Users/addUser/handler.addUser
    package:
      patterns:
        - "Users/addUser/handler.py"
    events:
      - http:
          path: user
          method: POST
          cors: true
          authorizer:
            name: verify-token
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
          request:
            schemas:
              application/json: ${file(Users/user-schema.json)}
  # LOGIN
  login:
    handler: Login/login/handler.login
    package:
      patterns:
        - "Login/login/handler.py"
    events:
      - http:
          path: login
          method: POST
          cors: true

          request:
            schemas:
              application/json: ${file(Login/login/login-schema.json)}
  logout:
    handler: Login/logout/handler.logout
    package:
      patterns:
        - "Login/logout/handler.py"
    events:
      - http:
          path: logout
          method: GET
          cors: true
          authorizer:
            name: verify-token
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0  
resources:
  Resources:
    Unauthorized:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
        ResponseType: "DEFAULT_4XX"
        RestApiId:
          Ref: "ApiGatewayRestApi"           

